name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Rust ${{ matrix.cfg_release_channel }}
    env:
      CFG_RELEASE_CHANNEL: ${{ matrix.cfg_release_channel }}
    strategy:
      matrix:
        cfg_release_channel: [stable, beta, nightly]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust ${{ matrix.cfg_release_channel }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.cfg_release_channel }}

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --all-features --verbose

      - name: Run tests
        run: cargo test --all-features --verbose

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
